apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-ghoul
  labels:
    app: discord-ghoul
spec:
  replicas: 10
  selector:
    matchLabels:
      app: discord-ghoul
  template:
    metadata:
      labels:
        app: discord-ghoul
    spec:
      containers:

      - name: ghoul-front
        image: docker.io/kidmortal/ghoul-front 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: http://localhost:5000
        
      - name: ghoul-server
        image: docker.io/kidmortal/ghoul-server  
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
