version: "3.7"
services:
  front:
    image: ghoul-front
    build: ./ghoul-front/
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    ports:
      - "80:80"
    networks:
      - main
  server:
    image: ghoul-server
    build: ./ghoul-server/
    ports:
      - "5000:5000"
    networks:
      - main
networks:
  main:
    driver: bridge
