version: "3.7"
services:
  front:
    image: ghoul-front
    build: ./ghoul-front/
    networks: ["default"]
    restart: always
    environment:
      - REACT_APP_API_URL=localhost:5000
    ports:
      - 3000:3000
    depends_on:
      - server
  server:
    image: ghoul-server
    build: ./ghoul-server/
    ports:
      - "5000:5000"
